"""App installs: upstream Flathub as the source, KosherOS as the gatekeeper.

Nobody on the system can install a flatpak directly — malcontent blocks
users, and polkit denies the stock Flatpak system-helper actions to
everyone. Installs happen only here, in kosherd, and only for refs on the
allowlist (/etc/kosher/catalog.json), which the admin (later the portal)
controls.

What actually enforces this (verified in the VM):
  1. polkit denies the Flatpak system-helper actions to every non-root
     subject, so a user running `flatpak install` gets "system operation
     Deploy not allowed"; user-scope installs are blocked by malcontent;
  2. this module checks every requested ref against the catalog before
     asking flatpak to do anything.
The remote also carries a flatpak *filter* rendered from the catalog, which
keeps unapproved apps out of enumeration (so nothing unapproved is even
discoverable). Note it is NOT a boundary against root — root can install
anything, which is fine because nobody can become root on KosherOS.

Installs run on a worker thread and report progress back through a callback
so the app store can show a live progress bar.
"""

from __future__ import annotations

import json
import logging
import threading
from collections import deque
from pathlib import Path

try:
    import gi

    gi.require_version("Flatpak", "1.0")
    from gi.repository import Flatpak, GLib  # noqa: E402
except (ImportError, ValueError):  # pragma: no cover - only where libflatpak
    # is absent. The catalog, ledger, filter rendering and appstream parsing
    # below need none of it, so they stay unit-testable off-device.
    Flatpak = None
    GLib = None

log = logging.getLogger(__name__)

CATALOG_PATH = Path("/etc/kosher/catalog.json")
FILTER_PATH = Path("/etc/kosher/flathub.filter")
# Apps install system-wide, so who asked for one is not recoverable from
# flatpak afterwards — kosherd records it here for the admin app.
LEDGER_PATH = Path("/var/lib/kosher/installs.json")
REMOTE = "flathub"


class AppError(Exception):
    pass


def load_catalog() -> dict:
    try:
        return json.loads(CATALOG_PATH.read_text())
    except FileNotFoundError:
        return {"apps": []}
    except ValueError as e:
        raise AppError(f"catalog is not valid JSON: {e}") from e


def allowed_refs() -> set[str]:
    return {a["ref"] for a in load_catalog().get("apps", [])}


def render_filter(refs: set[str]) -> str:
    """The filter file contents for a set of approved refs."""
    lines = [
        "# Generated by kosherd from /etc/kosher/catalog.json. DO NOT EDIT.",
        "# Only approved applications may be pulled from this remote.",
        "allow runtime/*",
    ]
    lines += [f"allow app/{ref}/*/*" for ref in sorted(refs)]
    return "\n".join(lines) + "\n"


def write_remote_filter() -> None:
    """Render the catalog into a flatpak remote filter (defense in depth).

    A filter containing any `allow` line makes deny the default, so only
    approved apps — plus the runtimes they need — can come from the remote.
    """
    FILTER_PATH.parent.mkdir(parents=True, exist_ok=True)
    FILTER_PATH.write_text(render_filter(allowed_refs()))

    installation = Flatpak.Installation.new_system(None)
    try:
        remote = installation.get_remote_by_name(REMOTE, None)
    except GLib.Error:
        log.warning("remote %s is not configured; filter written but not applied", REMOTE)
        return
    remote.set_filter(str(FILTER_PATH))
    installation.modify_remote(remote, None)
    log.info("applied flatpak remote filter (%d approved apps)", len(allowed_refs()))


def save_catalog(catalog: dict) -> None:
    """Persist the allowlist and re-apply the remote filter."""
    CATALOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    tmp = CATALOG_PATH.with_suffix(".tmp")
    tmp.write_text(json.dumps(catalog, indent=2) + "\n")
    tmp.replace(CATALOG_PATH)
    write_remote_filter()


def approve(ref: str, name: str = "", summary: str = "") -> None:
    catalog = load_catalog()
    apps_list = catalog.setdefault("apps", [])
    if any(a["ref"] == ref for a in apps_list):
        raise AppError(f"{ref} is already approved")
    entry = {"ref": ref, "name": name or ref}
    if summary:
        entry["summary"] = summary
    # What the Store needs to look like a store: which shelf the app sits
    # on and which icon to draw. Taken from the remote's own metadata here,
    # once, so the Store itself never parses a 40 MB catalogue — it reads
    # this file and local icon files, and opens instantly.
    try:
        known = {a["ref"]: a for a in _load_index()}.get(ref)
    except Exception:  # noqa: BLE001 - metadata is a nicety; approval is not
        known = None
    if known:
        if known.get("categories"):
            entry["categories"] = list(known["categories"])
        if known.get("icon"):
            entry["icon"] = known["icon"]
    apps_list.append(entry)
    apps_list.sort(key=lambda a: a.get("name", a["ref"]).lower())
    save_catalog(catalog)
    log.info("approved app %s", ref)


def unapprove(ref: str) -> None:
    catalog = load_catalog()
    before = len(catalog.get("apps", []))
    catalog["apps"] = [a for a in catalog.get("apps", []) if a["ref"] != ref]
    if len(catalog["apps"]) == before:
        raise AppError(f"{ref} is not on the approved list")
    save_catalog(catalog)
    log.info("removed app %s from the approved list", ref)


# -- searching the remote ----------------------------------------------------

_APPSTREAM_MAX_AGE = 24 * 3600
_index_cache: tuple[float, list[dict]] | None = None


def _arch() -> str:
    return Flatpak.get_default_arch() if Flatpak is not None else "x86_64"


def _appstream_path() -> Path:
    return Path(
        f"/var/lib/flatpak/appstream/{REMOTE}/{_arch()}/active/appstream.xml.gz"
    )


def ensure_appstream() -> None:
    """Fetch/refresh the remote's app metadata if it is missing or stale."""
    import time

    path = _appstream_path()
    fresh = path.exists() and (time.time() - path.stat().st_mtime) < _APPSTREAM_MAX_AGE
    if fresh:
        return
    installation = Flatpak.Installation.new_system(None)
    installation.update_appstream_sync(REMOTE, Flatpak.get_default_arch(), None)


_XML_LANG = "{http://www.w3.org/XML/1998/namespace}lang"
APP_COMPONENT_TYPES = frozenset({
    "desktop-application", "desktop", "console-application", None,
})


def _untranslated(component, tag: str) -> str:
    """The English text for a tag.

    AppStream repeats <name>/<summary> once per language; the untranslated
    entry is the one with no xml:lang. Taking the first match gives whatever
    translation happens to come first (GIMP came back in Arabic), which also
    wrecks search ranking.
    """
    fallback = ""
    for element in component.findall(tag):
        if element.get(_XML_LANG) is None:
            return (element.text or "").strip()
        fallback = fallback or (element.text or "").strip()
    return fallback


def parse_appstream(path: Path) -> list[dict]:
    """Parse an appstream catalogue into [{ref, name, summary}].

    Kept separate from caching and availability filtering so it can be
    tested directly: two shipped bugs lived here (a localized name winning
    over the English one, and Flathub's legacy component type hiding 47
    apps including Firefox).
    """
    import gzip
    import xml.etree.ElementTree as ET

    index: list[dict] = []
    with gzip.open(path, "rb") as fh:
        for _event, element in ET.iterparse(fh, events=("end",)):
            if element.tag != "component":
                continue
            # Flathub mixes the modern "desktop-application" type with the
            # legacy "desktop" one (Firefox uses it) — accept both, plus
            # console apps; skip runtimes, addons and localisation packs.
            if element.get("type") in APP_COMPONENT_TYPES:
                app_id = (element.findtext("id") or "").removesuffix(".desktop")
                name = _untranslated(element, "name") or app_id
                summary = _untranslated(element, "summary")
                if app_id:
                    index.append({"ref": app_id, "name": name, "summary": summary,
                                  "categories": _categories(element),
                                  "icon": _cached_icon(element)})
            element.clear()
    return index


def _categories(component) -> list[str]:
    """The freedesktop menu categories a component declares.

    The Store groups apps by these (Network, Office, Game and so on), which
    is what makes it a store rather than a list. Order is kept: the first
    is the one the publisher considers primary.
    """
    node = component.find("categories")
    if node is None:
        return []
    found = []
    for category in node.findall("category"):
        text = (category.text or "").strip()
        if text and text not in found:
            found.append(text)
    return found


def _cached_icon(component) -> str:
    """The file name of the icon flatpak caches locally for this component.

    AppStream offers several icon kinds; "cached" is the one the remote
    ships alongside the catalogue and flatpak writes under the appstream
    directory, so it costs no network and no unpacking to draw.
    """
    best = ""
    best_size = -1
    for icon in component.findall("icon"):
        if icon.get("type") != "cached":
            continue
        name = (icon.text or "").strip()
        if not name:
            continue
        try:
            size = int(icon.get("height") or icon.get("width") or 0)
        except ValueError:
            size = 0
        # Prefer the largest that is not bigger than we draw (128 px).
        score = size if size <= 128 else 128 - size
        if score > best_size:
            best, best_size = name, score
    return best


def icon_file(entry: dict, size: int = 128) -> str:
    """Where an approved app's icon actually is on this machine, or "".

    Looks beside the appstream catalogue flatpak already downloaded; the
    Store draws from there. An app with no cached icon falls back in the UI
    to its own themed icon (installed apps export one) and then to a
    generic one, so a missing file is never an error.
    """
    name = entry.get("icon") or ""
    if not name:
        return ""
    base = Path(f"/var/lib/flatpak/appstream/{REMOTE}/{_arch()}/active/icons")
    sizes = [f"{size}x{size}", "128x128", "64x64"]
    for folder in dict.fromkeys(sizes):
        candidate = base / folder / name
        if candidate.exists():
            return str(candidate)
    return ""


def _load_index() -> list[dict]:
    """The cached, availability-filtered search index."""
    global _index_cache

    path = _appstream_path()
    if not path.exists():
        return []
    mtime = path.stat().st_mtime
    if _index_cache is not None and _index_cache[0] == mtime:
        return _index_cache[1]

    index = parse_appstream(path)
    # Only keep apps the remote actually offers for this architecture.
    available = available_refs()
    index = [a for a in index if a["ref"] in available]
    index.sort(key=lambda a: a["name"].lower())
    _index_cache = (mtime, index)
    log.info("indexed %d apps from %s", len(index), REMOTE)
    return index


def search_remote(query: str, limit: int = 60) -> list[dict]:
    """Search every app the remote offers (for the admin's approval UI)."""
    ensure_appstream()
    needle = query.strip().lower()
    index = _load_index()
    if not needle:
        return index[:limit]

    def rank(app: dict) -> tuple[int, str]:
        name = app["name"].lower()
        if name == needle:
            return (0, name)
        if name.startswith(needle):
            return (1, name)
        if needle in name:
            return (2, name)
        return (3, name)

    hits = [
        a for a in index
        if needle in a["name"].lower()
        or needle in a["ref"].lower()
        or needle in a["summary"].lower()
    ]
    hits.sort(key=rank)
    return hits[:limit]


def _load_ledger() -> dict:
    try:
        return json.loads(LEDGER_PATH.read_text())
    except (OSError, ValueError):
        return {}


def record_install(ref: str, uid: int, username: str) -> None:
    ledger = _load_ledger()
    ledger[ref] = {"uid": uid, "username": username}
    LEDGER_PATH.parent.mkdir(parents=True, exist_ok=True)
    LEDGER_PATH.write_text(json.dumps(ledger, indent=2) + "\n")


def forget_install(ref: str) -> None:
    ledger = _load_ledger()
    if ledger.pop(ref, None) is not None:
        LEDGER_PATH.write_text(json.dumps(ledger, indent=2) + "\n")


def installed_details() -> list[dict]:
    """Installed apps with display names and who installed each one."""
    catalog = {a["ref"]: a for a in load_catalog().get("apps", [])}
    ledger = _load_ledger()
    installation = Flatpak.Installation.new_system(None)
    details = []
    for r in installation.list_installed_refs(None):
        if r.get_kind() != Flatpak.RefKind.APP:
            continue
        ref = r.get_name()
        entry = ledger.get(ref, {})
        details.append({
            "ref": ref,
            "name": r.get_appdata_name() or catalog.get(ref, {}).get("name") or ref,
            "size": r.get_installed_size(),
            "installed_by": entry.get("username", ""),
            "installed_by_uid": entry.get("uid", -1),
            "approved": ref in catalog,
        })
    details.sort(key=lambda a: a["name"].lower())
    return details


def installed_refs() -> set[str]:
    installation = Flatpak.Installation.new_system(None)
    return {
        r.get_name() for r in installation.list_installed_refs(None)
        if r.get_kind() == Flatpak.RefKind.APP
    }


def installed_ref_string(app_id: str) -> str:
    installation = Flatpak.Installation.new_system(None)
    for r in installation.list_installed_refs(None):
        if r.get_kind() == Flatpak.RefKind.APP and r.get_name() == app_id:
            return r.format_ref()
    raise AppError(f"{app_id} is not installed")


def resolve_remote_ref(app_id: str) -> str:
    """Find the real ref for an app id on the remote.

    Branches are not always 'stable' (some apps ship 'master' or a version),
    so resolve rather than guess — this also fails early and clearly when a
    catalog entry names an app the remote doesn't have.
    """
    installation = Flatpak.Installation.new_system(None)
    arch = Flatpak.get_default_arch()
    matches = [
        r for r in installation.list_remote_refs_sync(REMOTE, None)
        if r.get_kind() == Flatpak.RefKind.APP
        and r.get_name() == app_id
        and r.get_arch() == arch
    ]
    if not matches:
        raise AppError(f"{app_id} is not available on {REMOTE} for {arch}")
    matches.sort(key=lambda r: (r.get_branch() != "stable", r.get_branch()))
    return matches[0].format_ref()


def available_refs() -> set[str]:
    """App ids the remote actually offers for this architecture."""
    installation = Flatpak.Installation.new_system(None)
    arch = Flatpak.get_default_arch()
    return {
        r.get_name() for r in installation.list_remote_refs_sync(REMOTE, None)
        if r.get_kind() == Flatpak.RefKind.APP and r.get_arch() == arch
    }


class AppManager:
    """Queues flatpak jobs and reports progress.

    flatpak cannot run two transactions against the same installation at
    once, so jobs run one at a time — but requests are QUEUED, never
    refused: someone can click install on several apps and walk away. Queued
    jobs report a "Queued" status until their turn comes.
    """

    def __init__(self, on_progress, on_finished):
        """on_progress(ref, percent, status); on_finished(ref, ok, error)."""
        self._on_progress = on_progress
        self._on_finished = on_finished
        self._lock = threading.Lock()
        self._queue: deque[tuple[str, object]] = deque()
        self._pending: set[str] = set()   # queued or running
        self._running: str | None = None
        self._worker: threading.Thread | None = None

    @property
    def pending(self) -> set[str]:
        with self._lock:
            return set(self._pending)

    def install(self, ref: str) -> None:
        if ref not in allowed_refs():
            raise AppError(f"{ref} is not on the approved app list")
        self._enqueue(ref, self._do_install)

    def remove(self, ref: str) -> None:
        self._enqueue(ref, self._do_remove)

    def _enqueue(self, ref: str, work) -> None:
        with self._lock:
            if ref in self._pending:
                raise AppError(f"{ref} is already in progress")
            self._pending.add(ref)
            self._queue.append((ref, work))
            # The job being worked on is no longer in the queue, so count it
            # too — otherwise the first waiting job reports "0 ahead".
            position = len(self._queue) + (1 if self._running else 0)
            if self._worker is None or not self._worker.is_alive():
                self._worker = threading.Thread(target=self._drain, daemon=True)
                self._worker.start()
        if position > 1:
            self._on_progress(ref, 0, f"Queued ({position - 1} ahead)")

    def _drain(self) -> None:
        while True:
            with self._lock:
                if not self._queue:
                    self._worker = None
                    return
                ref, work = self._queue.popleft()
                self._running = ref
            try:
                work(ref)
            except Exception as e:  # noqa: BLE001 - reported to the caller
                # GLib.Error carries .message; anything else stringifies. Asking for
                # the attribute avoids depending on GLib being importable here.
                message = getattr(e, "message", None) or str(e)
                log.error("%s failed: %s", ref, message)
                self._finish(ref, False, message)
            else:
                self._finish(ref, True, "")

    def _finish(self, ref: str, ok: bool, error: str) -> None:
        with self._lock:
            self._pending.discard(ref)
            if self._running == ref:
                self._running = None
        self._on_finished(ref, ok, error)

    def _transaction(self, ref: str) -> Flatpak.Transaction:
        installation = Flatpak.Installation.new_system(None)
        transaction = Flatpak.Transaction.new_for_installation(installation, None)

        def on_new_operation(_tx, operation, progress):
            progress.connect(
                "changed",
                lambda p: self._on_progress(ref, p.get_progress(), p.get_status() or ""),
            )
            log.info("%s: %s", ref, operation.get_ref())

        transaction.connect("new-operation", on_new_operation)
        # Never let a transaction stall waiting on a console prompt.
        transaction.set_no_interaction(True)
        return transaction

    def _do_install(self, ref: str) -> None:
        self._on_progress(ref, 0, "Looking up…")
        full_ref = resolve_remote_ref(ref)
        transaction = self._transaction(ref)
        transaction.add_install(REMOTE, full_ref, None)
        self._on_progress(ref, 0, "Starting…")
        transaction.run(None)

    def _do_remove(self, ref: str) -> None:
        transaction = self._transaction(ref)
        transaction.add_uninstall(installed_ref_string(ref))
        self._on_progress(ref, 0, "Removing…")
        transaction.run(None)
