"""App installs: upstream Flathub as the source, KosherOS as the gatekeeper.

Nobody on the system can install a flatpak directly — malcontent blocks
users, and polkit denies the stock Flatpak system-helper actions to
everyone. Installs happen only here, in kosherd, and only for refs on the
allowlist (/etc/kosher/catalog.json), which the admin (later the portal)
controls.

What actually enforces this (verified in the VM):
  1. polkit denies the Flatpak system-helper actions to every non-root
     subject, so a user running `flatpak install` gets "system operation
     Deploy not allowed"; user-scope installs are blocked by malcontent;
  2. this module checks every requested ref against the catalog before
     asking flatpak to do anything.
The remote also carries a flatpak *filter* rendered from the catalog, which
keeps unapproved apps out of enumeration (so nothing unapproved is even
discoverable). Note it is NOT a boundary against root — root can install
anything, which is fine because nobody can become root on KosherOS.

Installs run on a worker thread and report progress back through a callback
so the app store can show a live progress bar.
"""

from __future__ import annotations

import json
import logging
import threading
from pathlib import Path

import gi

gi.require_version("Flatpak", "1.0")
from gi.repository import Flatpak, GLib  # noqa: E402

log = logging.getLogger(__name__)

CATALOG_PATH = Path("/etc/kosher/catalog.json")
FILTER_PATH = Path("/etc/kosher/flathub.filter")
REMOTE = "flathub"


class AppError(Exception):
    pass


def load_catalog() -> dict:
    try:
        return json.loads(CATALOG_PATH.read_text())
    except FileNotFoundError:
        return {"apps": []}
    except ValueError as e:
        raise AppError(f"catalog is not valid JSON: {e}") from e


def allowed_refs() -> set[str]:
    return {a["ref"] for a in load_catalog().get("apps", [])}


def write_remote_filter() -> None:
    """Render the catalog into a flatpak remote filter (defense in depth).

    A filter containing any `allow` line makes deny the default, so only
    approved apps — plus the runtimes they need — can come from the remote.
    """
    lines = [
        "# Generated by kosherd from /etc/kosher/catalog.json. DO NOT EDIT.",
        "# Only approved applications may be pulled from this remote.",
        "allow runtime/*",
    ]
    lines += [f"allow app/{ref}/*/*" for ref in sorted(allowed_refs())]
    FILTER_PATH.parent.mkdir(parents=True, exist_ok=True)
    FILTER_PATH.write_text("\n".join(lines) + "\n")

    installation = Flatpak.Installation.new_system(None)
    try:
        remote = installation.get_remote_by_name(REMOTE, None)
    except GLib.Error:
        log.warning("remote %s is not configured; filter written but not applied", REMOTE)
        return
    remote.set_filter(str(FILTER_PATH))
    installation.modify_remote(remote, None)
    log.info("applied flatpak remote filter (%d approved apps)", len(allowed_refs()))


def installed_refs() -> set[str]:
    installation = Flatpak.Installation.new_system(None)
    return {
        r.get_name() for r in installation.list_installed_refs(None)
        if r.get_kind() == Flatpak.RefKind.APP
    }


def installed_ref_string(app_id: str) -> str:
    installation = Flatpak.Installation.new_system(None)
    for r in installation.list_installed_refs(None):
        if r.get_kind() == Flatpak.RefKind.APP and r.get_name() == app_id:
            return r.format_ref()
    raise AppError(f"{app_id} is not installed")


def resolve_remote_ref(app_id: str) -> str:
    """Find the real ref for an app id on the remote.

    Branches are not always 'stable' (some apps ship 'master' or a version),
    so resolve rather than guess — this also fails early and clearly when a
    catalog entry names an app the remote doesn't have.
    """
    installation = Flatpak.Installation.new_system(None)
    arch = Flatpak.get_default_arch()
    matches = [
        r for r in installation.list_remote_refs_sync(REMOTE, None)
        if r.get_kind() == Flatpak.RefKind.APP
        and r.get_name() == app_id
        and r.get_arch() == arch
    ]
    if not matches:
        raise AppError(f"{app_id} is not available on {REMOTE} for {arch}")
    matches.sort(key=lambda r: (r.get_branch() != "stable", r.get_branch()))
    return matches[0].format_ref()


def available_refs() -> set[str]:
    """App ids the remote actually offers for this architecture."""
    installation = Flatpak.Installation.new_system(None)
    arch = Flatpak.get_default_arch()
    return {
        r.get_name() for r in installation.list_remote_refs_sync(REMOTE, None)
        if r.get_kind() == Flatpak.RefKind.APP and r.get_arch() == arch
    }


class AppManager:
    """Serializes flatpak transactions and reports progress."""

    def __init__(self, on_progress, on_finished):
        """on_progress(ref, percent, status); on_finished(ref, ok, error)."""
        self._on_progress = on_progress
        self._on_finished = on_finished
        self._lock = threading.Lock()
        self._busy: str | None = None

    @property
    def busy_with(self) -> str | None:
        return self._busy

    def install(self, ref: str) -> None:
        if ref not in allowed_refs():
            raise AppError(f"{ref} is not on the approved app list")
        self._start(ref, self._do_install)

    def remove(self, ref: str) -> None:
        self._start(ref, self._do_remove)

    def _start(self, ref: str, work) -> None:
        with self._lock:
            if self._busy is not None:
                raise AppError(f"busy installing {self._busy}; try again shortly")
            self._busy = ref
        threading.Thread(target=self._run, args=(ref, work), daemon=True).start()

    def _run(self, ref: str, work) -> None:
        try:
            work(ref)
        except Exception as e:  # noqa: BLE001 - reported to the caller
            message = e.message if isinstance(e, GLib.Error) else str(e)
            log.error("%s failed: %s", ref, message)
            self._finish(ref, False, message)
        else:
            self._finish(ref, True, "")

    def _finish(self, ref: str, ok: bool, error: str) -> None:
        with self._lock:
            self._busy = None
        self._on_finished(ref, ok, error)

    def _transaction(self, ref: str) -> Flatpak.Transaction:
        installation = Flatpak.Installation.new_system(None)
        transaction = Flatpak.Transaction.new_for_installation(installation, None)

        def on_new_operation(_tx, operation, progress):
            progress.connect(
                "changed",
                lambda p: self._on_progress(ref, p.get_progress(), p.get_status() or ""),
            )
            log.info("%s: %s", ref, operation.get_ref())

        transaction.connect("new-operation", on_new_operation)
        # Never let a transaction stall waiting on a console prompt.
        transaction.set_no_interaction(True)
        return transaction

    def _do_install(self, ref: str) -> None:
        self._on_progress(ref, 0, "Looking up…")
        full_ref = resolve_remote_ref(ref)
        transaction = self._transaction(ref)
        transaction.add_install(REMOTE, full_ref, None)
        self._on_progress(ref, 0, "Starting…")
        transaction.run(None)

    def _do_remove(self, ref: str) -> None:
        transaction = self._transaction(ref)
        transaction.add_uninstall(installed_ref_string(ref))
        self._on_progress(ref, 0, "Removing…")
        transaction.run(None)
